- name: Install Docker dependencies
  apt: name={{ item }} state=latest
  with_items:
   - apt-transport-https
   - ca-certificates
   - curl
   - gnupg2
   - software-properties-common

- name: Install Docker apt-key
  apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Install Docker repository
  apt_repository:
    repo: deb https://download.docker.com/linux/debian stretch stable
    state: present

- name: Install Docker CE
  apt:
    name: docker-ce
    update_cache: yes
    state: latest

- name: Start the Docker service, if not running
  service:
    name: docker
    state: started
